### ISSUE TITLE
Wrong channel index in APDcam data import

### ISSUE THREAD

**Issue by astechow** [fusion-flap/flap_apdcam#1]
The following line should select the correct channel to import:
https://github.com/fusion-flap/flap_apdcam/blob/d469afac0da0def7b0d47c9cb9782835b3341196/flap_apdcam.py#L169

However, `fnames[ch_proc[i]-1]` only indexes the correct channel if all channels are set to record during measurement. This will load the wrong channel if there is a gap in the channel list, or fail entirely with an error if the channel number to load exceeds the number of channels recorded.
This can be fixed for example by changing fthis to: `fnames[ch_index[i]]`

**Comment by sandorzoletnik** [comment]
Corrected, the problem was that fnames  contains only the file names found on the disk.
